name: barber
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  animated_background: ^2.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  another_carousel_pro: ^1.0.1  # Replaced carousel_slider
  shimmer: ^3.0.0 # Added for the shiny button effect

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
