// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcQJZZlNOVNnN1-OxujAm74UpYPZTcwL8',
    appId: '1:529410369995:web:7ef9bd58ed918eb26a2e4e',
    messagingSenderId: '529410369995',
    projectId: 'barber-9133c',
    authDomain: 'barber-9133c.firebaseapp.com',
    storageBucket: 'barber-9133c.firebasestorage.app',
    measurementId: 'G-2K9SDY4EC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2B5pxU4_lT5CxPcF0B_dTFS7aFvlU6FY',
    appId: '1:529410369995:android:ece4317fcccaf7556a2e4e',
    messagingSenderId: '529410369995',
    projectId: 'barber-9133c',
    storageBucket: 'barber-9133c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMz9hwI8LRClyS0HRAwo5L7peL8L2SUqk',
    appId: '1:529410369995:ios:8db99d7f987355336a2e4e',
    messagingSenderId: '529410369995',
    projectId: 'barber-9133c',
    storageBucket: 'barber-9133c.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMz9hwI8LRClyS0HRAwo5L7peL8L2SUqk',
    appId: '1:529410369995:ios:8db99d7f987355336a2e4e',
    messagingSenderId: '529410369995',
    projectId: 'barber-9133c',
    storageBucket: 'barber-9133c.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcQJZZlNOVNnN1-OxujAm74UpYPZTcwL8',
    appId: '1:529410369995:web:efdd1861c9d63c326a2e4e',
    messagingSenderId: '529410369995',
    projectId: 'barber-9133c',
    authDomain: 'barber-9133c.firebaseapp.com',
    storageBucket: 'barber-9133c.firebasestorage.app',
    measurementId: 'G-JLN4401W1B',
  );
}
